Document OpenSSL development package dependency
Document that the OpenSSL development package is required to build and install
the "cryptography" Python package on Linux.

On Ubuntu 16.04 with Python 3.5.2, this fixes the following error:

    $ pip install -e .[plugins]
    ...
    Collecting cryptography (from girder==2.1.0)
    ...
    Running setup.py install for cryptography ... error
    ...
    build/temp.linux-x86_64-3.5/_openssl.c:434:30: fatal error: openssl/opensslv.h: No such file or directory

Reference:
https://cryptography.io/en/latest/installation/#building-cryptography-on-linux