Print help for 'girder-install' with no args
Before, if you ran girder-install with no args, you would
get a cryptic error message such as this:

AttributeError: 'Namespace' object has no attribute 'func'

Now, the help message is printed instead, which indicates that
girder-install needs to be ran with args.