Fix bug in test_resource.yml
After we delete we can't register test_collection because we no longer
have access to the _id field (we've deleted the collection)  so when we
try to delete it again it throws an error:

"One or more undefined variables: 'dict object' has no attribute '_id'"

Removing the register resolves this problem