Only generate webpackHelper configuration when building a plugin
This fixes a bug in --watch-plugin caused by #2305

```
Loading "plugin.js" tasks...ERROR
>> TypeError: Cannot read property 'module' of undefined
```

raised at grunt_tasks/plugin.js:481 because when a plugin is configured,
but not built, the configuration object is not created.